---
# tasks file for dotvim
- name: "Including Installation tasks"
  ansible.builtin.include_tasks: install.yml

- name: "Including vim setup tasks"
  ansible.builtin.include_tasks: vim_setup.yml

- name: "Including Pathogen"
  ansible.builtin.include_tasks: pathogen.yml
  when:
    - dotvim_pathogen.enable|bool
