source 	$HOME/.vim/custom/settings.vim	"my custom settings
source 	$HOME/.vim/custom/maps.vim	"keyboard maps

" --- Including external modules ---
source	$HOME/.vim/custom/plug.vim	"plugins manager settings
